### ISSUE TITLE
Publish the package in npm

### ISSUE THREAD

**Issue by dacoto** [IconKit/IconKit#2]
Publish the package in npm, to be able to download it directly and update it easily.

**Comment by ShankerRaj** [comment]
It's already in npmjs.com [https://www.npmjs.com/package/icon-kit](url)

**Comment by ShankerRaj** [comment]
> Publish the package in npm, to be able to download it directly and update it easily.
It's already in npmjs.com [https://www.npmjs.com/package/icon-kit](url)
